apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-training-service
  namespace: lucascarvalho
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-training
  template:
    metadata:
      labels:
        app: model-training
    spec:
      containers:
      - name: training-service
        image: luccaspc/recommendation-service:1.5
        env:
        - name: MODEL_PATH
          value: "/app/shared/models/fpgrowth_model.pkl"
        - name: CENTRAL_DATASET_PATH
          value: "/central_data/2023_spotify_ds2.csv"
        - name: USER_DATASET_PATH
          value: "/user_data/2023_spotify_songs.csv"
        - name: CHECK_INTERVAL
          value: "30"
        volumeMounts:
        - name: model-storage
          mountPath: /app/shared/models
        - name: dataset-volume
          mountPath: /central_data
          readOnly: true
        - name: user-dataset-volume
          mountPath: /user_data
          readOnly: true
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2G"
            cpu: "1"
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-storage-pvc
      - name: dataset-volume
        hostPath:
          path: /home/datasets/spotify
          type: Directory
      - name: user-dataset-volume
        hostPath:
          path: /home/lucascarvalho/tp2/dataset
          type: Directory
          
