apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-training-service
  namespace: lucascarvalho
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-training
  template:
    metadata:
      labels:
        app: model-training
    spec:
      containers:
      - name: training-service
        image: luccaspc/recommendation-service:latest
        env:
        - name: MODEL_PATH
          value: "/app/shared/models/fpgrowth_model.pkl"
        - name: DATASET_PATH
          value: "/data/2023_spotify_ds1.csv"
        volumeMounts:
        - name: model-storage
          mountPath: /app/shared/models
        - name: dataset-volume
          mountPath: /data
          readOnly: true
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-storage-pvc
      - name: dataset-volume
        hostPath:
          path: /home/datasets/spotify
          type: Directory
          