apiVersion: apps/v1
kind: Deployment
metadata:
  name: lucascarvalho-recommender-api
  namespace: lucascarvalho
  annotations:
    argocd-image-updater.argoproj.io/image-list: api-service=luccaspc/api-service
    argocd-image-updater.argoproj.io/api-service.update-strategy: latest
    argocd-image-updater.argoproj.io/api-service.allow-tags: regexp:.*
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lucascarvalho-recommender-api
  template:
    metadata:
      labels:
        app: lucascarvalho-recommender-api
    spec:
      containers:
      - name: api-service
        image: luccaspc/api-service:1.0
        ports:
        - containerPort: 52043
        env:
        - name: API_VERSION
          value: "1.4"
        - name: MODEL_PATH
          value: "/app/shared/models/fpgrowth_model.pkl"
        - name: PORT
          value: "52043"
        volumeMounts:
        - name: model-storage
          mountPath: /app/shared/models
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-storage-pvc
