apiVersion: batch/v1
kind: Job
metadata:
  name: model-training-service
  namespace: lucascarvalho
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 900 
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: training-service
        image: luccaspc/recommendation-service:latest
        env:
        - name: MODEL_PATH
          value: "/app/shared/models/fpgrowth_model.pkl"
        - name: DATASET_PATH
          value: "/data/2023_spotify_ds1.csv"
        volumeMounts:
        - name: model-storage
          mountPath: /app/shared/models
        - name: dataset-volume
          mountPath: /data
          readOnly: true
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-storage-pvc
      - name: dataset-volume
        hostPath:
          path: /home/datasets/spotify
          type: Directory
