apiVersion: v1
kind: Service
metadata:
  name: recommender-api-service
  namespace: lucascarvalho
spec:
  selector:
    app: lucascarvalho-recommender-api
  ports:
  - protocol: TCP
    port: 52043
    targetPort: 52043
  type: ClusterIP